spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/clarim_diario
spring.datasource.username=postgres
spring.datasource.password=Pedro123

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:chave-de-desenvolvimento-testes-no-ambiente-local-1234}
jwt.expiracao-minutos=60

# Corrigido aqui:
google.client-id=${GOOGLE_CLIENT_ID:exemplo_client_id}

# Corrigido aqui (Adicionado o ${} e a estrutura correta):
stripe.secret-key=${STRIPE_API_KEY:sk_test_chave_ficticia_aqui}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_ficticio_aqui}

app.front-url=http://localhost:5173
